"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-d@#pnpg-drygrr742)4lhaj0z84g!&^s92ag1ebr6b14y0e31t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ... apps de django ...
    'tasks', # <--- Nuestras apps
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'uptasking_db',      # El nombre que creó en el Paso 4
        'USER': 'postgres',          # Su usuario de Postgres
        'PASSWORD': 'AqL341',   # <--- ¡PONGA SU CONTRASEÑA AQUÍ!
        'HOST': 'localhost',         # Generalmente es localhost
        'PORT': '5432',              # Puerto por defecto de Postgres
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# 1. Idioma por defecto (Para que las fechas digan "Ene" y no "Jan")
LANGUAGE_CODE = 'es-ar'

# 2. Zona Horaria (La clave para arreglar la hora)
# En lugar de 'UTC', ponemos la zona de Buenos Aires
TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

# 3. ¡IMPORTANTE! Mantenga esto en True.
# Esto le dice a Django: "Guarda en la BD en UTC (universal), 
# pero conviértelo a la hora local del usuario cuando lo muestres en pantalla".
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ... (Debajo de STATIC_ROOT) ...

# URL base para acceder a las fotos
MEDIA_URL = '/media/'

# Carpeta física donde se guardarán las fotos
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ... al final del archivo ...

# A dónde ir después de loguearse (si no iba a una url específica)
LOGIN_REDIRECT_URL = 'dashboard'

# A dónde ir después de salir (LOGOUT)
# Lo mandamos de vuelta al login para que se identifique de nuevo
LOGOUT_REDIRECT_URL = 'login'

LOGIN_URL = 'login'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'