# Generated by Django 6.0.1 on 2026-01-27 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Tarea')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_objetivo', models.DateField(verbose_name='Fecha Límite (Objetivo)')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha Real de Cierre')),
                ('avance', models.CharField(blank=True, max_length=100, verbose_name='Reporte de Avance')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones Finales')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('compartida_con', models.ManyToManyField(blank=True, related_name='tareas_compartidas', to=settings.AUTH_USER_MODEL, verbose_name='Compartir con')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_tareas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_objetivo'],
            },
        ),
    ]
