# Generated by Django 6.0.1 on 2026-01-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialavance',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos_tareas/'),
        ),
    ]
