# Generated by Django 6.0.1 on 2026-01-28 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_historialavance_archivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('bg-primary', 'Azul (Estratégico)'), ('bg-secondary', 'Gris (General)'), ('bg-success', 'Verde (Logística/Ventas)'), ('bg-danger', 'Rojo (Crítico/Urgente)'), ('bg-warning text-dark', 'Amarillo (Alerta)'), ('bg-info text-dark', 'Celeste (Inteligencia)'), ('bg-dark', 'Negro (Operaciones Especiales)')], default='bg-secondary', max_length=50)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='tasks.etiqueta', verbose_name='Etiquetas'),
        ),
    ]
