# Generated by Django 6.0.1 on 2026-01-29 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_etiqueta_tarea_etiquetas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialavance',
            options={},
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='creado',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='actualizado',
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='color',
            field=models.CharField(choices=[('bg-primary', 'Azul'), ('bg-secondary', 'Gris'), ('bg-success', 'Verde'), ('bg-danger', 'Rojo'), ('bg-warning text-dark', 'Amarillo'), ('bg-info text-dark', 'Celeste'), ('bg-dark', 'Negro')], default='bg-primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historialavance',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_adjuntos'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='avance',
            field=models.CharField(blank=True, help_text='Ej: 50%, En validación...', max_length=100),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='compartida_con',
            field=models.ManyToManyField(blank=True, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_ESPERA', 'En Espera'), ('EN_PROCESO', 'En Progreso'), ('EN_REVISION', 'En Revisión'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='tasks.etiqueta'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_objetivo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
