# Generated by Django 6.0.1 on 2026-01-31 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_proyecto_creado_el_proyecto_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
