# Generated by Django 6.0.1 on 2026-01-31 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_tarea_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialavance',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
