# Generated by Django 6.0.1 on 2026-01-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_historialavance_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='tareas', to='tasks.etiqueta'),
        ),
    ]
